const HOME_PAGE = {
    BACKGROUND: '#F5F5F5',
    TEXT: '#000000',
    TEXT_SECONDARY: '#9E9E9E',
    TEXT_THIRD: '#757575',
    TEXT_FOURTH: '#616161',
    TEXT_FIFTH: '#424242',
    NAVBAR: {
        NAV_TEXT: '#FFFFFF',
        NAV_HOVER_TEXT: '#FFFFFF',
        NAV_ACTIVE_TEXT: '#FFFFFF',
        NAV_BUTTON_BACKGROUND: '#FFFFFF',
        NAV_BUTTON_HOVER_BACKGROUND: '#FFFFFF',
        NAV_BUTTON_TEXT: '#FFFFFF',
        NAV_BUTTON_HOVER_TEXT: '#FFFFFF',
    },
    LANDINGS: {
        BACKGROUND: '#FFFFFF',
        TITLE: '#FFFFFF',
        DESCRIPTION: '#FFFFFF',
        BUTTON_BACKGROUND: '#FFFFFF',
        BUTTON_TEXT: '#FFFFFF',
        BUTTON_HOVER_BACKGROUND: '#FFFFFF',
        BUTTON_HOVER_TEXT: '#FFFFFF',
    }
}

export { HOME_PAGE };