const termsAndConditions = `
These terms of service, together with any documents and additional terms they incorporate by reference (collectively, these “Terms”), are entered into between the Deepchain Labs Foundation (the “Foundation,” “we,” “us,” and “our”) and you or the company or other legal entity that you represent (“you” or “your”).

Please read these Terms carefully as they govern your use of our site located at deepchainlabs.com and all associated sites (the “Website”) and our Services (defined below) and describe your rights and obligations and our disclaimers and limitations of legal liability. By accessing or using any part of the Website or the Services, you agree to become bound by the terms and conditions of these Terms.

If you use the Services on behalf of a company, organization (including a decentralized autonomous organization or “DAO”) or other entity then “you” includes you and that entity, and you represent and warrant that (a) you are an authorized representative of the entity with the authority to bind the entity to these Terms, and (b) you agree to these Terms on the entity’s behalf.

If you do not agree to these Terms or do not have authority to bind your organization on whose behalf you are using the Services to these Terms, you must not access or use our Website or the Services. Please carefully review the disclosures and disclaimers set forth in Section 8 in their entirety before accessing the Website, our Services, or using any software developed by the Foundation. Please refer to our privacy policy available at deepchainlabs.com/privacy-policy for information about how we collect, use, share and otherwise process information about you. In addition, you agree to comply with the Deepchain Labs Community Code of Conduct with respect to any interactions on or arranged through the Website.

We reserve the right, in our sole discretion, to modify these Terms from time to time. If we make changes, we will provide you with notice of such changes using commercially reasonable means, such as by sending an email, providing a notice through the Website or our Services or updating the date at the top of these Terms. Unless we say otherwise in our notice, any modifications are effective immediately, and your continued use of the Website or our Services will confirm your acceptance of the changes. If you do not agree to the amended Terms, you must stop using our Services.
`;

const service = `The Website enables users to access open source documentation and related services, including (without limitation) resources, data and computation services, information about the decentralized network of node operators that are selling usage of specific data via data feeds, APIs and various off-chain payment capabilities directly to smart contracts integrating Deepchain labs software (“Deepchain labs Network”), and resources for the Deepchain labs Network community (collectively such services, information, APIs, and resources related to the Deepchain labs Network are referred to as the “Services”). Some Services offered by us or other participants in the Deepchain labs Network require payment or otherwise 
involve the use of an underlying blockchain or other decentralized or permissioned infrastructure (“Distributed Ledger Technology”), which may require that you pay a fee, such as “gas” charges on the Ethereum network or other applicable blockchain network, for the computational resources required to perform a transaction on the particular Distributed Ledger Technology (such payments and fees, “Charges”). You acknowledge and agree that the Foundation has no control over any Distributed Ledger Technology transactions, the method of payment of any Charges, if applicable, or any actual payments of Charges, if applicable. Accordingly, you must ensure that you have a sufficient balance of the applicable Distributed Ledger Technology 
network tokens stored at your Distributed Ledger Technology-compatible wallet address (“Distributed Ledger Technology Address”) to complete any transaction on the Deepchain labs Network or the Distributed Ledger Technology before initiating such a transaction.`;

const trademarkGuidelines = `The Deepchain Labs Foundation (the “Foundation”) has developed these guidelines (“Guidelines”) to ensure that the Foundation trademarks and service marks (“Marks”) are properly displayed and used. As the owner of its Marks, the Foundation has exclusive rights to use its Marks and is obligated to prevent others from using its Marks inappropriately. If use of the Foundation’s Marks is authorized, it is expected that you will comply in all respects with the requirements and conditions set forth in these Guidelines and in any other guidelines promulgated by the Foundation. Nothing contained in these Guidelines should be construed as granting, by implication, estoppel, or otherwise, any license or right in 
and to the Marks or other intellectual property owned by the Foundation. Unauthorized use of any of the Marks or the Foundation’s other intellectual property may violate the law. All rights not expressly granted herein are reserved by the Foundation.`;

const disclaimer = `These Guidelines are not intended to serve as legal advice. Should you have questions regarding your legal rights or duties, please consult your own attorney. 
Should you have further questions regarding the policies of the Foundation with respect to its Marks, please contact <a href="mailto:info@deepchainlabs.com" class="t-text-blue-500">info@deepchainlabs.com</a>.`;

export { termsAndConditions, service, trademarkGuidelines, disclaimer };
